/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Assignment as PrismaAssignment,
  Application as PrismaApplication,
  Task as PrismaTask,
  Employee as PrismaEmployee,
} from "@prisma/client";

export class AssignmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AssignmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.assignment.count(args);
  }

  async assignments(
    args: Prisma.AssignmentFindManyArgs
  ): Promise<PrismaAssignment[]> {
    return this.prisma.assignment.findMany(args);
  }
  async assignment(
    args: Prisma.AssignmentFindUniqueArgs
  ): Promise<PrismaAssignment | null> {
    return this.prisma.assignment.findUnique(args);
  }
  async createAssignment(
    args: Prisma.AssignmentCreateArgs
  ): Promise<PrismaAssignment> {
    return this.prisma.assignment.create(args);
  }
  async updateAssignment(
    args: Prisma.AssignmentUpdateArgs
  ): Promise<PrismaAssignment> {
    return this.prisma.assignment.update(args);
  }
  async deleteAssignment(
    args: Prisma.AssignmentDeleteArgs
  ): Promise<PrismaAssignment> {
    return this.prisma.assignment.delete(args);
  }

  async getApplication(parentId: string): Promise<PrismaApplication | null> {
    return this.prisma.assignment
      .findUnique({
        where: { id: parentId },
      })
      .application();
  }

  async getTask(parentId: string): Promise<PrismaTask | null> {
    return this.prisma.assignment
      .findUnique({
        where: { id: parentId },
      })
      .task();
  }

  async getEmployee(parentId: string): Promise<PrismaEmployee | null> {
    return this.prisma.assignment
      .findUnique({
        where: { id: parentId },
      })
      .employee();
  }
}
